# Generated by Django 5.0.7 on 2024-07-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sneaker price in $')),
                ('release_date', models.DateField()),
                ('description', models.TextField(blank=True, verbose_name='Sneaker description')),
                ('is_published', models.BooleanField(default=False, verbose_name='Sneaker is published to the store')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.brand', verbose_name='Sneaker brand')),
            ],
            options={
                'verbose_name': 'Sneaker',
                'verbose_name_plural': 'Sneakers',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sneakers/images')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sneakers.sneaker')),
            ],
        ),
    ]
