# Generated by Django 5.0.7 on 2024-07-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers', '0003_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='is_popular',
            field=models.BooleanField(default=True, verbose_name='Sneaker is popular'),
        ),
    ]
